#! /bin/bash

sxhkd -c ~/.config/bspwm/themes/bspwm_yellow/sxhkd/sxhkdrc &
conky -c conky -c .config/bspwm/themes/bspwm_yellow/conky/conky_dark.conf &
numlockx &
nitrogen --restore &
picom --config ~/.config/bspwm/themes/bspwm_yellow/picom/picom.conf &
#picom --config ~/.config/bspwm/themes/bspwm_yellow/picom-ftlabs/picom.conf &
xsetroot -cursor_name left_ptr &

~/.config/bspwm/themes/bspwm_yellow/scripts/polybar.sh &

firefox &
telegram-desktop -startintray &
lutris &


#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+750+90
bspc rule -a TelegramDesktop state=floating follow=off
bspc rule -a Firefox state=floating rectangle=1600x900+160+90 desktop='^1'
bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a dmenu rectangle=900x22+610+90
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
bspc rule -a Inkscape desktop='^3'
bspc rule -a Blender desktop='^2'

bspc monitor -d 󰖟 󰳫        󰊗 

bspc config border_width         0
bspc config window_gap          10

bspc config normal_border_color "#123354"
bspc config active_border_color "#123354"
bspc config focused_border_color "#f5f7fa"
bspc config presel_feedback_color "#123354"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	true
bspc config borderless_monocle	true
bspc config gapless_monocle	false
bspc config paddingless_monocle	true
